component-definition: ./internal/testdata/oscal/component-definition-heterogeneous.json
catalog: ./internal/testdata/oscal/catalog.json
plugins:
  ocm:
    policy-dir: ./internal/testdata/ocm/policies
    policy-results-dir: ./internal/testdata/ocm/policy-results
    output-dir: /tmp/outputs
    temp-dir: /tmp/ocm
    policy-set-name: "Managed Kubernetes"
    namespace: "c2p"
  kyverno:
    policy-dir: ./internal/testdata/kyverno/policy-resources
    policy-results-dir: ./internal/testdata/kyverno/policy-reports
    temp-dir: /tmp/kyverno
    output-dir: /tmp/outputs
advanced:
  max-plugin-timeout: 3
