name: "Pull Request Labeler"
on:
- pull_request

permissions: {}

jobs:
  labeler:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 #v5
